// Assets.tsx - Department data for the college website
const defaultHodImage = '/images/BVRIT.png';

export const Assets = {
  DepartmentData: {
    cse: {
      name: 'Computer Science and Engineering',
      heroImage: '/images/departments/ecm.png',
      about: "The Department of Computer Science and Engineering at B V Raju Institute of Technology, Visakhapatnam, was established in 2002 and provides a perfect academic and research environment complemented by excellence in teaching. The Department offers B.Tech. and M.Tech. (CSE and SE) programs. The department has a comprehensive curriculum on topics related to all aspects of Computer Science and Engineering with an emphasis on practical learning. The course structure is up-to-date and includes courses on nascent topics to equip our students with the latest developments in Computer Science and Engineering. The Department has state-of-the-art infrastructure and computing equipment supported by high-speed Ethernet and wireless networks. Student organizations like the ACM Chapter are active throughout the year. Our faculty members aim at delivering top-class education, blending their rich research experience with classroom teaching. The department has undertaken many research projects funded by both government agencies and foreign research societies. The CSE Department currently has 49 full-time faculty members, some of whom are cross-listed with related departments such as Basic Science, EEE, ECE, and Mechanical. We also draw on the expertise of a few Visiting Professors from foreign universities and industry. The department has a UG intake of 240 students. Roughly 80% of these students get jobs in industries, and 10-15% go for Master's programs and research.",
      hodMessage: "A warm welcome to CSE@BVRIT’s Institute of Information Technology. The Computer Science and Engineering (CSE) department at BVRIT’s Institute of Information Technology has its roots in the institute established in 2002. While it was primarily focused on academics at inception, its ambit expanded to include M.Tech programs, research, placements, a research center, and NBA accreditations (2009 and 2017), leading to its current name. The CSE Department focuses on academics, creative research, and good placements in three broad areas of computer science: Computer Science and Engineering, including basic concepts, number theory, complexity theory, graph theory, coding theory, algorithms, data structures, cryptography, and security; Computer Systems and Software, including computer architecture, operating systems, programming languages, compilers, software engineering, database systems, graphics and visualization, communication networks, and distributed computing; and Intelligent Systems, including data mining, machine learning, artificial intelligence, optimization, information retrieval, and scientific applications. These academic and research activities find expression through publications in premier international journals and conferences. CSE is also involved in numerous scientific initiatives at the institute, state, national, and international levels, including sponsored research projects, consultancy, government programs, hackathons, journal editorships, workshops, and conferences.",
      hodName: 'Dr. Mohan Mahanty',
      hodImage: defaultHodImage,
      vision: "To become a nationally recognized leader in computer science education, research, and innovation, producing graduates who are highly sought after by industry and academia.",
      mission: [
        "To provide a dynamic and creative learning environment that fosters a deep understanding of computer science fundamentals.",
        "To encourage practical problem-solving.",
        "To inspire lifelong learning and ethical responsibility."
      ],
      faculty: [
        { sno: 1, name: 'Mr.B.Dinesh Reddy', designation: 'HOD' },
        { sno: 2, name: 'Dr.N.Tirupathi Rao', designation: 'Professor' },
        { sno: 3, name: 'Dr.S.Naga Mallik Raj', designation: 'Assoc. Professor(Senior Scale)' },
        { sno: 4, name: 'Dr.CH.Swapnapriya', designation: 'Assoc. Professor(Senior Scale)' },
        { sno: 5, name: 'Dr.P.Hemantry kohan', designation: 'Assoc. Professor(Senior Scale)' },
        { sno: 6, name: 'Dr.K.N.UmaMaheswara Rao', designation: 'Assoc. Professor(Senior Scale)' },
        { sno: 7, name: 'Dr.Chandrasekhar sekhem Dinesh', designation: 'Assoc. Professor' },
        { sno: 8, name: 'Dr.K.Rohit Kumar', designation: 'Assoc. Professor' },
        { sno: 9, name: 'Mrs.P.Sandya', designation: 'Sr.Asst. Professor' },
        { sno: 10, name: 'Ms.V.Swathi', designation: 'Sr.Asst. Professor' },
        { sno: 11, name: 'Mrs.G.Kumari', designation: 'Sr.Asst. Professor' },
        { sno: 12, name: 'Mrs.Benu.Nekkanti', designation: 'Sr.Asst. Professor' },
        { sno: 13, name: 'Mr.J.G.Pandit Samuel', designation: 'Sr.Asst. Professor' },
        { sno: 14, name: 'Mrs.P. Pratima rani', designation: 'Asst. Professor' },
        { sno: 15, name: 'Ms.A.Priyaka Devi', designation: 'Asst. Professor' },
        { sno: 16, name: 'Ms.K.Visala', designation: 'Asst. Professor' },
        { sno: 17, name: 'Mrs.Nalini', designation: 'Asst. Professor' },
        { sno: 18, name: 'Mrs.N.Srutha', designation: 'Asst. Professor' },
        { sno: 19, name: 'Ms.J.Priyanka', designation: 'Asst. Professor' },
        { sno: 20, name: 'Ms.V.Pushpa', designation: 'Asst. Professor' },
        { sno: 21, name: 'Mr.V.V.Rama Lingasastry', designation: 'Asst. Professor' },
        { sno: 22, name: 'Ms. V. Anusha', designation: 'Asst. Professor' },
        { sno: 23, name: 'Ms.M.Manju Bhargavi', designation: 'Asst. Professor' },
        { sno: 24, name: 'Ms.D.Saroja', designation: 'Asst. Professor' },
        { sno: 25, name: 'Mrs.Ch.Sridevi', designation: 'Asst. Professor' },
        { sno: 26, name: 'Mrs.S.Anuradha', designation: 'Asst. Professor' },
        { sno: 27, name: 'Mrs.V.Sravani Rajya Lakshmi', designation: 'Asst. Professor' },
        { sno: 28, name: 'Mrs. M.Rukmini Durga', designation: 'Asst. Professor' },
        { sno: 29, name: 'Mr.T.Mounika', designation: 'Asst. Professor' },
        { sno: 30, name: 'Dr. P.V.G.Prasad', designation: 'Asst. Professor' },
        { sno: 31, name: 'Ms. Benkata Anusha', designation: 'Asst. Professor' },
        { sno: 32, name: 'Mr. Venkata Rajulu Pilli', designation: 'Asst. Professor' },
        { sno: 33, name: 'Mr. Shaik Jani', designation: 'Asst. Professor' },
        { sno: 34, name: 'Venkat Lakshmi Korukonda', designation: 'Asst. Professor' },
        { sno: 35, name: 'Sindhu Baratam', designation: 'Asst. Professor' },
        { sno: 36, name: 'Sailaja Kunche', designation: 'Asst. Professor' },
        { sno: 37, name: 'Kurapati Sudha', designation: 'Asst. Professor' },
        { sno: 38, name: 'Nagu Vadlana', designation: 'Asst. Professor' },
        { sno: 39, name: 'R Jaya', designation: 'Asst. Professor' },
        { sno: 40, name: 'Ch Anusha', designation: 'Asst. Professor' },
        { sno: 41, name: 'Y. Srilatha', designation: 'Asst. Professor' },
        { sno: 42, name: 'L. Sai Saramya', designation: 'Asst. Professor' },
        { sno: 43, name: 'Y. Anil Kumar', designation: 'Asst. Professor' },
        { sno: 44, name: 'Bhupathirao Lakinana', designation: 'Asst. Professor' },
        { sno: 45, name: 'Sasanapuri Chandini', designation: 'Asst. Professor' },
        { sno: 46, name: 'Mr.Bharadwaja Chepuru', designation: 'Asst. Professor' },
        { sno: 47, name: 'Ms.S.Vani', designation: 'Asst. Professor' },
        { sno: 48, name: 'Mr. Dega Balakotaiah', designation: 'Asst. Professor' },
        { sno: 49, name: 'Ms.O.Jasmine', designation: 'Teaching Asst.' },
        { sno: 50, name: 'Ms.M.Jyothirmayi', designation: 'Teaching Asst.' },
      ]
    },

    aids: {
      name: 'Artificial Intelligence and Data Science',
      heroImage: 'https://i.ibb.co/z3Hrc6F/Whats-App-Image-2025-08-04-at-13-22-10-da2d5090.jpg',
      about: "B.Tech. in Artificial Intelligence and Data Science (AI & DS) is an undergraduate program introduced in 2020 with advanced learning solutions imparting knowledge of advanced innovations like artificial intelligence, data science, machine learning, and deep learning. The main goal of artificial intelligence and data science is to program computers to use example data or experience to solve a given problem. In recent times, data science has emerged as one of the most high-growth, dynamic, and gainful careers in technology. This course aims at providing not only the core technologies such as artificial intelligence, data mining, and data modeling but also gives intensive inputs in areas of machine learning and big data analytics. Through this course, students will gain cross-disciplinary skills across fields such as statistics, computer science, machine learning, and logic. Data scientists may have career opportunities in healthcare, business, e-commerce, social networking companies, climatology, biotechnology, genetics, and other important areas. Our mission is to cultivate Industry-Academia partnerships, drive collaborative research with other domains, and equip our talents to contribute to multidisciplinary projects by translating the developed technology into real-world impacts.",
      hodMessage: "Welcome to the Department of Artificial Intelligence & Data Science. The B.Tech. program in Artificial Intelligence and Data Science (AI & DS) is an undergraduate initiative introduced in 2020, offering advanced educational solutions that delve into the realm of cutting-edge innovations such as artificial intelligence, data science, machine learning, and deep learning. Our department's mission is to seamlessly integrate superior education with valuable industry contributions. Our department is consistently pushing the boundaries of innovation. With the aim of providing students a harmonious blend of intellectual exploration and hands-on practical exposure, our ultimate goal is to equip them to effectively address a wide array of societal needs. Within our department, students are nurtured and groomed to evolve into exceptional software professionals, including roles such as Data Engineers, Data Analysts, AI Engineers, or Team Leaders in industry, or to become entrepreneurs in their own innovative way. I am confident that in the times ahead, numerous students from our department will leave an indelible mark both nationally and internationally in the field of AI & DS, bringing pride to our institution. Our department boasts a dynamic faculty, comprising youthful and driven educators whose expertise spans the entire spectrum of AI & DS disciplines. Coupled with our diligent and dedicated students, as well as a vibrant work culture, our Department of AI & DS forms the academic nucleus of the institute. We firmly believe in our potential to excel, fostering a mindset of self-reliance, confidence, commitment, and responsibility toward our nation. This philosophy underscores the spirit of our youthful and dynamic AI & DS department – one that strives to construct careers, enrich intellects, and provide an unforgettable educational experience that resonates for a lifetime. I extend my heartfelt best wishes for their endeavors. Good luck to each one of you!",
      hodName: 'Dr. T.V. Madhusudan Rao',
      hodImage: defaultHodImage,
      vision: "To be globally competent in the field of Artificial Intelligence and Data Science by creating technically potential professionals for future industry requirements and undertaking high-quality domain research to serve society and the betterment of mankind.",
      mission: [
        "To empower students with adequate technical and analytical skills by undertaking research and development in the area of AI & DS.",
        "To emphasize an innovative teaching-learning process in order to produce professionals with AI & DS domain expertise.",
        "To provide ethical and human values along with problem-solving skills, leadership qualities, and team spirit to solve the complex engineering problems of modern society."
      ],
      faculty: [
        { sno: 1, name: 'Dr.T.V.Madhusudhana Rao', designation: 'HOD-Professor' },
        { sno: 2, name: 'Dr.Bhiogade Girish Eknath', designation: 'Assoc.Prof (Senior Scale)' },
        { sno: 3, name: 'Dr.Peter Praveen', designation: 'Assoc.Prof (Senior Scale)' },
        { sno: 4, name: 'Dr.Brajesh Kumar', designation: 'Assoc.Prof' },
        { sno: 5, name: 'Dr.P.Visweswara Rao', designation: 'Assoc.Prof' },
        { sno: 6, name: 'Mr.Gourisankar Nayak', designation: 'Sr.Asst.Prof' },
        { sno: 7, name: 'Ms.I.Manikumari', designation: 'Sr.Asst.Prof' },
        { sno: 8, name: 'Mr.D.Chandramouli', designation: 'Asst.Prof' },
        { sno: 9, name: 'Ms.N.R.S.Lakshmi Prasanthi', designation: 'Asst.Prof' },
        { sno: 10, name: 'Mrs.B.Madhavi', designation: 'Asst.Prof' },
        { sno: 11, name: 'Ms.M.Sharmila', designation: 'Asst.Prof' },
        { sno: 12, name: 'Ms.P.Deekshita', designation: 'Asst.Prof' },
        { sno: 13, name: 'Ms.B.Prameela', designation: 'Asst.Prof' },
        { sno: 14, name: 'Mr. Chavali Amaresh', designation: 'Asst. Prof.' },
        { sno: 15, name: 'Mr. S. Ranjeeth', designation: 'Asst. Prof.' },
        { sno: 16, name: 'Mr. Mathi Mohana Venkateswara Rao', designation: 'Asst. Prof.' },
        { sno: 17, name: 'Ms. Guggilam Navya', designation: 'Asst. Prof.' },
        { sno: 18, name: 'Mr. Kiran Kumar Kaveti', designation: 'Asst. Prof.' },
        { sno: 19, name: 'Mr. Murali Krishna Nangedda', designation: 'Asst. Prof.' },
        { sno: 20, name: 'Mr.Ch.Yamini Sankar', designation: 'Asst. Prof.' },
        { sno: 21, name: 'Mr.R.Srinivasarao', designation: 'Asst. Prof.' },
        { sno: 22, name: 'Mr. Bathula Anil Babu', designation: 'Asst. Prof.' },
      ]
    },

    it: {
      name: 'Information Technology',
      heroImage: '/images/departments/it.png',
      about: "The Department of Information Technology at B V Raju Institute of Technology (BVRIT) has been active in teaching and research since its inception in 2002. Currently, about 15 committed faculty members work in the department. The Department of Information Technology offers a four-year undergraduate program and a two-year postgraduate program in the field of Information Technology. The department was started in 2002 with state-of-the-art infrastructural facilities right from its inception. It is continuously thriving to impart quality education and a competitive spirit among students for academic excellence. The consistent university ranks in competitive exams such as GATE, GRE, TOEFL, and IELTS, and the campus placements achieved by the students indicate the aspiration of our department. The department has made significant progress within a few years. Its objective is to develop logical thinking through problem-solving among students and to train them in the latest technologies as per industrial needs. The department contains efficient and eminent faculty, including senior faculty, mostly with B.Tech and M.Tech backgrounds.",
      hodMessage: "It's my pleasure to welcome you to the Department of Information Technology, established in the year 2002. Information Technology is a passionate and well-established department with new technologies and eminent experts working as faculty peers. Information Technology focuses on installing, implementing, and maintaining software and applying it in industries to meet their business needs. I ensure the Department of Information Technology will provide an exceptional learning experience that will enable students to become independent thinkers and success makers in creating real-time applications in their chosen career path. I wish you all the best! Come and join us.",
      hodName: 'Dr. G. Neelima',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence in high-quality education and research, producing globally competent IT professionals with ethical and human values to meet the needs of the Information Technology sector and related services.",
      mission: [
        "To impart high-quality education through innovative teaching-learning practices, resulting in strong software and hardware knowledge and skills to enable students to meet the challenges of the IT profession.",
        "To facilitate faculty and students to carry out research work by providing the latest necessary facilities and a conducive environment.",
        "To mold students into effective professionals with necessary communication skills, team spirit, leadership qualities, managerial skills, integrity, social & environmental responsibility, and lifelong learning ability with professional ethics and human values."
      ],
      faculty: [
        { sno: 1, name: 'Dr.GullipalliNeelima', designation: 'HOD-Professor' },
        { sno: 2, name: 'Dr.B.Prasad', designation: 'Professor' },
        { sno: 3, name: 'Dr.T.Eswara Rao', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Mrs.G.Jyothi', designation: 'Sr.Asst. Prof.' },
        { sno: 5, name: 'Mr.Ch.Srinivasa Reddy', designation: 'Sr.Asst. Prof.' },
        { sno: 6, name: 'Mr.G.Ravikumar', designation: 'Sr.Asst. Prof.' },
        { sno: 7, name: 'Mrs.G.Mani', designation: 'Sr.Asst. Prof.' },
        { sno: 8, name: 'Ms.P.Pavithra', designation: 'Asst.Prof' },
        { sno: 9, name: 'Ms.Y.Jayalakshmi', designation: 'Asst.Prof' },
        { sno: 10, name: 'Ms.K.Lashmi Prasanna', designation: 'Asst.Prof' },
        { sno: 11, name: 'Mrs.Mruna Dubey', designation: 'Asst.Prof' },
        { sno: 12, name: 'Ms. R. Naga Shirisha', designation: 'Asst.Prof' },
        { sno: 13, name: 'Mr. C. Kalyan Chakravarthi', designation: 'Asst.Prof' },
        { sno: 14, name: 'Mr. Kiran Kumar Kalagadda', designation: 'Asst. Prof.' },
        { sno: 15, name: 'Mr. Yalamanchili Bhanuprasad', designation: 'Asst. Prof.' },
        { sno: 16, name: 'Mr. Simhadri Chinna Gopi', designation: 'Asst. Prof.' },
        { sno: 17, name: 'Mr. T Narasimha Rao', designation: 'Asst. Prof.' },
        { sno: 18, name: 'Mr. Sureshbabu Amarthaluri', designation: 'Asst. Prof.' },
        { sno: 19, name: 'Mr. Sheik Bhadar Saheb', designation: 'Asst. Prof.' },
        { sno: 20, name: 'Mr. Y. Rama Mohan', designation: 'Asst. Prof.' },
        { sno: 21, name: 'Mr.Gullapalli Praveen Kumar', designation: 'Asst. Prof.' },
        { sno: 22, name: 'Mrs.Parvathy Chennupati', designation: 'Asst. Prof.' },
      ]
    },

    ece: {
      name: 'Electronics and Communication Engineering (ECE)',
      heroImage: '/images/departments/ece.png',
      about: "The Department of Electronics and Communication Engineering (ECE) at B V Raju Institute of Technology (Autonomous) was established in 2002 with an intake of 180 for imparting state-of-the-art knowledge in Electronics and Communication Engineering and allied areas. The department offers postgraduate programs in VLSI and Embedded Systems (M.Tech – VLSI&ES) and Communication Engineering (M.Tech – ECE), with an initial intake of 18, later decreased to 9 in the academic year 2019-20. The department has set up laboratories with excellent infrastructure in the areas of Electronics, Communication, Advanced Electronics, and Advanced Communications. The B.Tech program of the department is accredited by the NBA and has a JNTU-GV recognized research center. More than 90% of student admissions occur every year, and the department has qualified faculty from reputed institutes with an average of 25% doctorates (maintaining the SFR as per AICTE norms). The department has received a DST SERB project worth Rs. 85,63,830, AICTE Modrobs funding worth Rs. 15,09,412, and has 20 patents and consultancy projects worth Rs. 7,37,000. The average placement rate is more than 90% for the last 5 years, and the average academic performance is more than 92%. The department has a strong research environment with 133 publications in the last 5 years. It organizes various technical, non-technical, co-curricular, extracurricular, and extension activities to transform students into engineers, leaders, and entrepreneurs.",
      hodMessage: "It is our earnest desire to develop this department into a cognizant center of learning with excellent faculty and good administration, for the development and welfare of the society from which we draw our resources and inspiration. The institution is facilitated with the best capabilities to impart skills, both theoretical and practical, for updating technical knowledge with the latest expertise in the respective fields of Engineering and Technology. I greet all those who wish to associate themselves with this center of learning and invite them to join the BVRIT's Family.",
      hodName: 'Dr. R. Uma Maheswari',
      hodImage: defaultHodImage,
      vision: "To be a Centre of Excellence in the field of Electronics and Communication Engineering through high-quality education, research, and consultancy, producing professionals with global standards, ethical and human values, and a commitment to serving society.",
      mission: [
        "To impart high-quality education with innovative practices in the teaching-learning process to empower students to take up professional/career challenges.",
        "To foster research activities for faculty and students by providing state-of-the-art facilities and a conducive environment.",
        "To promote consultancy work among faculty and students by enhancing Industry-Institute interaction.",
        "To transform students into effective professionals with communication skills, leadership qualities, managerial skills, integrity, team spirit, social & environmental responsibility, and lifelong learning ability with professional ethics & human values."
      ],
      faculty: [
          { sno: 1, name: 'Dr.J.Sudhakar', designation: 'Principal' },
          { sno: 2, name: 'Dr.R.Uma Maheswari', designation: 'HOD Assoc.Prof(selection Grade)' },
          { sno: 3, name: 'Dr.Ch.Ramesh Babu', designation: 'Dean IQAC-Assoc.Prof(selection Grade)' },
          { sno: 4, name: 'Dr.A.Naga Jyothi', designation: 'Professor' },
          { sno: 5, name: 'Dr.K.Srinivasa Naik', designation: 'Professor' },
          { sno: 6, name: 'Dr.M.Karuna', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 7, name: 'Dr.A.Sampath Dakshina Murthy', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 8, name: 'Dr.V.Sateesh', designation: 'Assoc. Prof.' },
          { sno: 9, name: 'Dr.A.Vyasa Bharadwaja', designation: 'Assoc. Prof.' },
          { sno: 10, name: 'Dr.D.Pratap Kumar', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 11, name: 'Dr.P.Nalini', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 12, name: 'Dr.P.Suneetha', designation: 'Assoc. Prof.' },
          { sno: 13, name: 'Dr.P.V.Sai Charishma', designation: 'Assoc. Prof.' },
          { sno: 14, name: 'Ms.Y.Sukanya', designation: 'Sr.Asst.Prof' },
          { sno: 15, name: 'Mr.P.Tirumala Rao', designation: 'Asst.Prof' },
          { sno: 16, name: 'Mrs.B.Bharani', designation: 'Asst.Prof' },
          { sno: 17, name: 'Mr.S.Ravi Kumar', designation: 'Sr.Asst.Prof' },
          { sno: 18, name: 'Mrs.K.Lakshmi', designation: 'Sr.Asst.Prof' },
          { sno: 19, name: 'Mrs.J.Vijayasree', designation: 'Asst.Prof' },
          { sno: 20, name: 'Mr.K.Chaitanya', designation: 'Sr.Asst.Prof' },
          { sno: 21, name: 'Mr.Srinivash Roula', designation: 'Asst.Prof' },
          { sno: 22, name: 'Mr.J.Siddartha Varma', designation: 'Asst.Prof' },
          { sno: 23, name: 'Ms.P.Mamathadevi', designation: 'Asst.Prof' },
          { sno: 24, name: 'Mr.P.Gopi Krishna', designation: 'Asst.Prof' },
          { sno: 25, name: 'Mr.Allam Venkatesh', designation: 'Asst.Prof' },
          { sno: 26, name: 'Mr.A.Satyanarayana Varma', designation: 'Asst.Prof' },
          { sno: 27, name: 'Mrs.Ch.Eswari Sai Sindhu Priya', designation: 'Asst.Prof' },
          { sno: 28, name: 'Mrs.G.Laxmi Priyanka', designation: 'Asst.Prof' },
          { sno: 29, name: 'Mr.S.Venkata Anand', designation: 'Asst.Prof' },
          { sno: 30, name: 'Ms.K.Kalyani', designation: 'Asst.Prof' },
          { sno: 31, name: 'Ms.K.Saujanya', designation: 'Asst.Prof' },
          { sno: 32, name: 'Ms.G.S.Charitha', designation: 'Asst.Prof' },
          { sno: 33, name: 'Ms.A.Usha Rani', designation: 'Asst.Prof' },
          { sno: 34, name: 'Mr.P.Vijaya Bhaskar', designation: 'Asst.Prof' },
          { sno: 35, name: 'Mr.J.Sumadeep', designation: 'Asst.Prof' },
          { sno: 36, name: 'Mr. G Sudheer', designation: 'Asst.Prof' },
      ]
    },

    eee: {
      name: 'Electrical and Electronics Engineering',
      heroImage: '/images/departments/eee.png',
      about: "The Department of Electrical and Electronics Engineering at B V Raju Institute of Technology has been active in teaching and research since its inception in 2002. The department offers a four-year undergraduate program in Electrical & Electronics Engineering and a two-year postgraduate course in Power and Industrial Drives. The department has state-of-the-art laboratories with the latest equipment and modern technical software. It has a team of richly experienced and dedicated faculty from reputed institutes. Currently, about 38 committed faculty members are engaged in research in the areas of Electrical Machines, Control Systems, Power Systems, High Voltage Engineering, Power Electronics, etc. Faculty are encouraged to take independent initiatives with collective responsibility in all relevant academic and R&D dimensions like innovative teaching, student projects, and research supervision, as well as continuing education through organizing conferences, symposia, etc. The department has funded project grants worth Rs. 55 Lakhs. The latest teaching and learning techniques are adapted to train students to explore, create, challenge, and lead. The department faculty addresses the emotional and psychological needs of the students through a strong counseling system. The EEE department consistently maintains results of nearly 90%. About 60% of the students are placed through campus drives. As a part of its social responsibilities to uplift the surrounding community, the department conducts community welfare programs.",
      hodMessage: "It is my pleasure to welcome you to the Department of Electrical & Electronics Engineering at BVRIT’s Institute of Information Technology (Autonomous). The department has been active in teaching and research since its inception in 2002. The growing utilization of electrical energy and the penetration of renewable energy are decisive prerequisites for the rapid development of industry. The department aims to train students by imparting the latest knowledge in the fields of Electrical, Electronics, and other allied areas, with a focus on ethical and human values. The department offers academic programs: B.Tech (Electrical & Electronics Engineering) and M.Tech (Power and Industrial Drives). The curriculum has been enriched at regular intervals by the Board of Studies members, drawn from international and national level reputed academic, research, and industrial organizations. The department is supported by well-qualified and experienced faculty with rich and varied teaching and research exposure. Many of them are from standard Indian Institutions like IITs and NITs. Most of the faculty members have published or presented papers in reputed national and international journals and conferences. Electrical Engineers have great opportunities for employment in state and central electricity boards like APGENCO, APTRANSCO, BHEL, NTPC, NHPC, etc.",
      hodName: 'Dr. Pudi Sekhar',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence for high-quality education and research in the field of Electrical and Electronics Engineering, generating world-class professionals practicing ethical & human values with a commitment to service for the betterment of society.",
      mission: [
        "To impart high-quality education with innovative practices in the teaching-learning process to empower students to take up professional/career challenges.",
        "To foster a spirit of research amongst faculty and students by providing state-of-the-art facilities and a conducive environment.",
        "To transform students into effective professionals with communication skills, leadership qualities, managerial capabilities, team spirit, integrity, social and environmental responsibility, lifelong learning ability, and ethical & human values."
      ],
      faculty: [
          { sno: 1, name: 'Dr.P.Sekhar', designation: 'HOD Assoc. Prof.(Selection Grade)' },
          { sno: 2, name: 'Dr.K.Durga Syam Prasad', designation: 'Professor' },
          { sno: 3, name: 'Dr.R.S.Ravi Sankar', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 4, name: 'Dr.K.K.Deepika', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 5, name: 'Dr.K.Venkatanagaraju', designation: 'Assoc. Prof.(Senior Scale)' },
          { sno: 6, name: 'Dr.M.Lakshmi SivaSai Kumar', designation: 'Assoc. Prof.' },
          { sno: 7, name: 'Dr.B.Trinadha', designation: 'Assoc. Prof.' },
          { sno: 8, name: 'Dr.B.Omkar Lakshmi Jagan', designation: 'Assoc. Prof.' },
          { sno: 9, name: 'Dr.Jayanta Kumar Sahu', designation: 'Assoc. Prof.' },
          { sno: 10, name: 'Dr.Subhendu Sekhar Sahoo', designation: 'Assoc. Prof.' },
          { sno: 11, name: 'Mrs.K.Sravanthi', designation: 'Sr.Asst.Prof' },
          { sno: 12, name: 'Ms.B.Jyothi', designation: 'Sr.Asst.Prof' },
          { sno: 13, name: 'Mr.K.Sravan Kumar', designation: 'Asst. Prof.' },
          { sno: 14, name: 'Mr.V.Vivek Viswanadh', designation: 'Asst. Prof.' },
          { sno: 15, name: 'Mr.Rajesh Tanna', designation: 'Asst.Prof' },
          { sno: 16, name: 'Ms.B.Sonia', designation: 'Sr.Asst.Prof' },
          { sno: 17, name: 'Mr.P.Suresh Kumar', designation: 'Sr.Asst.Prof' },
          { sno: 18, name: 'Mr.A.V.Satyanarayana', designation: 'Asst.Prof' },
          { sno: 19, name: 'Ms.V.Venkata Lakshmi', designation: 'Asst.Prof' },
          { sno: 20, name: 'Mr.K.Avinash', designation: 'Asst.Prof' },
          { sno: 21, name: 'Mr.R.Ganesh', designation: 'Asst.Prof' },
      ]
    },

    me: {
      name: 'Mechanical Engineering',
      heroImage: '/images/departments/me.png',
      about: "The Department of Mechanical Engineering at B V Raju Institute of Technology (BVRIT) has been active in teaching and research since its inception in 2004. The department offers a four-year undergraduate program with an intake of 180 in Mechanical Engineering and a two-year postgraduate program with an intake of 18 in Machine Design. It has also been recognized as a 'Research Center'. The Department of Mechanical Engineering was first started in 2004 with an aim to provide quality engineers not only to our nation but also to other countries. The field of study includes technical subject areas such as thermal engineering, design, manufacturing, materials sciences, CAD/CAM, etc. Mechanical Engineers are people with a pragmatic ability to design, model physical systems, to analyze, and to create, all within the framework of socio-humanistic needs. The strength of our department is derived from its excellent faculty, comprehensive facilities, and the success of our graduates in the job market. Many of our faculty are highly recognized in their fields and have earned a good name and fame in teaching. Our students are provided a solid engineering education with a focus on creativity, innovation, and a strong ethical responsibility. The mechanical engineering program prepares graduates with strong leadership qualities. These leadership qualities and our program's high technical standards generate strong interest from industries and employers across the region. I am happy to inform you that some of our graduates are pursuing their postgraduate studies worldwide.",
      hodMessage: "It brings me great joy and a sense of privilege to extend my warmest welcome to you as you step into the realm of Mechanical Engineering. Among the most ancient and all-encompassing branches of engineering, mechanical engineering holds a pivotal position in advancing safety, economic prosperity, enjoyment, and the overall global quality of life.",
      hodName: 'Dr. S. Rambabu',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence in academics, research, and consultancy in the field of Mechanical Engineering, producing globally competent professionals with ethical and human values for national/international development.",
      mission: [
        "To impart high-quality education through innovative teaching and learning methods to enable students to be globally competent to face the challenges of their profession/career.",
        "To promote research activities amongst faculty and students by providing necessary facilities and environment.",
        "To mold students into effective professionals with necessary communication skills, team spirit, leadership qualities, industry-managerial skills, integrity, social & environmental responsibility, and lifelong learning ability with professional ethics & human values.",
        "To promote consultancy work amongst faculty and students by enhancing industry-institution interactions."
      ],
      faculty: [
          { sno: 1, name: 'Dr.Rambabu Sarimalla', designation: 'HOD. Assoc.Prof(selection Grade)' },
          { sno: 2, name: 'Dr. B. Sateesh', designation: 'Professor' },
          { sno: 3, name: 'Dr.R. Sundara Ramam', designation: 'Professor' },
          { sno: 4, name: 'Dr.K.S. Raghuram', designation: 'Assoc.Prof(Senior Scale)' },
          { sno: 5, name: 'Dr.V.S.V.Satyanarayana', designation: 'Assoc.Prof(Senior Scale)' },
          { sno: 6, name: 'Dr.V.Ranjith Kumar', designation: 'Assoc.Prof(Senior Scale)' },
          { sno: 7, name: 'Dr.V.Ranjan Ganguly', designation: 'Assoc.Prof' },
          { sno: 8, name: 'Dr.Y.Appalanaidu', designation: 'Assoc.Prof' },
          { sno: 9, name: 'Dr.K.Ismail', designation: 'Assoc.Prof' },
          { sno: 10, name: 'Dr.K.G.Durga Prasad', designation: 'Assoc.Prof' },
          { sno: 11, name: 'Dr.G.Satish', designation: 'Assoc.Prof' },
          { sno: 12, name: 'Dr.S.Sudhakar Babu', designation: 'Assoc.Prof' },
          { sno: 13, name: 'Dr.B.Siva Kumar', designation: 'Assoc.Prof' },
          { sno: 14, name: 'Mr.CH. Sivaramakrishna', designation: 'Sr.Asst.Prof' },
          { sno: 15, name: 'Mr.R. Rudhrabhi Ramu', designation: 'Asst.Prof' },
          { sno: 16, name: 'Mr.G. Santosh Kumar', designation: 'Asst.Prof' },
          { sno: 17, name: 'Mrs.B.Pavani Sri Kavya', designation: 'Asst.Prof' },
          { sno: 18, name: 'Mr.K.LeelaKumar', designation: 'Asst.Prof' },
          { sno: 19, name: 'Mr.B.Hemanth', designation: 'Sr.Asst.Prof' },
          { sno: 20, name: 'Mr.Nekkala Ganesh', designation: 'Asst.Prof' },
          { sno: 21, name: 'Ms.V.Naga Sudha', designation: 'Sr.Asst.Prof' },
          { sno: 22, name: 'Mr.P.H.J.Venkatesh', designation: 'Sr.Asst.Prof' },
          { sno: 23, name: 'Mr.B.Gangadhar', designation: 'Asst.Prof' },
          { sno: 24, name: 'Ms.G.Sridevi', designation: 'Asst.Prof' },
          { sno: 25, name: 'Ms.D.Prathyusha', designation: 'Asst.Prof' },
          { sno: 26, name: 'Mr.S.Sanyasi Rao', designation: 'Asst.Prof' },
          { sno: 27, name: 'Dr.Ch.Rohini Kumar', designation: 'Assoc.Prof' },
          { sno: 28, name: 'Dr.Ch.Bharat Kumar', designation: 'Assoc.Prof' },
          { sno: 29, name: 'Mr.Dhaneshwar Prasad Sahu', designation: 'Asst.Prof' },
          { sno: 30, name: 'Ms.B.Vineela Ratnam', designation: 'Asst.Prof' },
      ]
    },

    civil: {
        name: 'Civil Engineering',
        heroImage: '/images/departments/civil.png',
        about: "The Department of Civil Engineering has been part of the institute since 2011. The department has grown tremendously over the years and is now recognized as one of the major engineering departments in the state, offering a four-year undergraduate program in Civil Engineering. The department has an amalgam of experienced faculty, almost all of whom are qualified from premier institutions like IITs and NITs. The department is focusing on the special skills required for the Civil Engineering field along with regular academics. The department encourages students to take up projects based on societal problems. In addition, from the second year onwards, programming skills, problem-solving skills, and managerial skills are imparted. As a result, over 90% of students are able to get placements in core industries.",
        hodMessage: "It is a great opportunity to be Head of the Department of Civil Engineering. I feel proud to introduce the department's strengths and achievements. The Department of Civil Engineering is offering a UG course with an intake of 120 in B.Tech (Civil Engineering) and a postgraduate program with an intake of 18 in M.Tech (Transportation Engineering). The students of Civil Engineering are good in both academics as well as in extracurricular and co-curricular activities. Our students are provided with a solid engineering education, with a focus on creativity, innovation, and a strong ethical responsibility. The Civil Engineering program prepares graduates with strong leadership qualities. These leadership qualities and our program's high technical standards generate strong interest from industries and employers across the region.",
        hodName: 'Dr. Govinda Lalam',
        hodImage: defaultHodImage,
        vision: "To create high-quality Civil Engineers with a global perspective and to inculcate among them social consciousness, work ethics, and make them psychologically strong.",
        mission: [
          "To impart high-quality education with innovative practices in the teaching-learning process to empower students to fit competitively into present and future industrial requirements.",
          "To transform students into effective professionals by providing communication skills, leadership qualities, managerial ability, team spirit, and social responsibility to serve the nation, along with physical fitness and ethical and human values.",
          "To promote research activities amongst faculty and students by providing necessary facilities and a conducive environment.",
          "To promote consultancy work amongst faculty and students by enhancing industry-institution interactions."
        ],
        faculty: [
            { sno: 1, name: 'Dr.L.Govinda', designation: 'HOD-Assoc. Prof.' },
            { sno: 2, name: 'Dr.G.Tejaswi Laxmi Priyanka', designation: 'Assoc. Prof.' },
            { sno: 3, name: 'Dr.K.Ramesh Babu', designation: 'Assoc.Prof' },
            { sno: 4, name: 'Dr.G.Amulya', designation: 'Assoc. Prof.' },
            { sno: 5, name: 'Dr.S.Gayathri', designation: 'Assoc. Prof.' },
            { sno: 6, name: 'Dr.D.Sreeman', designation: 'Assoc. Prof.' },
            { sno: 7, name: 'Dr.A.Srija', designation: 'Assoc. Prof.' },
            { sno: 8, name: 'Dr.K.Dharithri', designation: 'Assoc. Prof.' },
            { sno: 9, name: 'Dr.P.SruthiSekhar', designation: 'Assoc. Prof.' },
            { sno: 10, name: 'Dr.G.Aravind Goud', designation: 'Assoc. Prof.' },
            { sno: 11, name: 'Mr.B.Brahmaiah', designation: 'Sr.Asst.Prof' },
            { sno: 12, name: 'Mr.K.Srinivas', designation: 'Sr.Asst.Prof' },
            { sno: 13, name: 'Ms.S.Kranthi Vijaya', designation: 'Sr.Asst. Prof.' },
            { sno: 14, name: 'Ms.A.V.S.L.Ramya', designation: 'Asst. Prof.' },
            { sno: 15, name: 'Mr.R.Rohit Babu', designation: 'Asst. Prof.' },
            { sno: 16, name: 'Ms.M.Yogaswarna', designation: 'Asst. Prof.' },
            { sno: 17, name: 'Mr.M.Baburao', designation: 'Asst.Prof' },
            { sno: 18, name: 'Mr.A.Teja', designation: 'Asst.Prof' },
            { sno: 19, name: 'Ms.T.Reshma Chandran', designation: 'Asst.Prof' },
            { sno: 20, name: 'Ms.K.Sree Sandhya', designation: 'Asst.Prof' },
            { sno: 21, name: 'Mr.B.Ashok Kumar', designation: 'Asst.Prof' },
        ]
    },

    acse: {
      name: 'Advanced Computer Science and Engineering',
      heroImage: '/images/departments/acse.png',
      about: "The Department of Advanced Computer Science and Engineering at B V Raju Institute of Technology, Visakhapatnam, was established in 2022. It provides a perfect academic and research environment complemented by excellence in teaching. The department offers B.Tech. programs in Cyber Security, Artificial Intelligence, and Data Science. It has a comprehensive curriculum on topics related to all aspects of Advanced Computer Science and Engineering with an emphasis on practical learning. The course structure is up-to-date and includes courses on nascent topics to equip our students with the latest developments in Computer Science and Engineering. The department has state-of-the-art infrastructure and computing equipment supported by high-speed Ethernet and wireless networks. Student organizations like the ACM Chapter are active throughout the year. Our faculty members aim to deliver top-class education, blending their rich research experience with classroom teaching. The department has undertaken many research projects funded by both government agencies and foreign research societies. The ACSE Department currently has 13 full-time faculty members, some of whom are cross-listed with related departments. The department has a UG intake of 240 students.",
      hodMessage: "A warm welcome to ACSE@BVRIT’s Institute of Information Technology. The ACSE Department focuses on academics, creative research, and good placements in three broad areas of advanced computer science: Computer Science and Engineering, including basic concepts, number theory, complexity theory, graph theory, coding theory, algorithms, data structures, cryptography, and security; Computer Systems and Software, including computer architecture, operating systems, programming languages, compilers, software engineering, database systems, graphics and visualization, communication networks, and distributed computing; and Intelligent Systems, including data mining, machine learning, artificial intelligence, optimization, information retrieval, and scientific applications. These academic and research activities find expression through publications in premier international journals and conferences. ACSE is also involved in numerous scientific initiatives at the institute, state, national, and international levels, including sponsored research projects, consultancy, government programs, hackathons, journal editorships, workshops, and conferences.",
      hodName: 'Mrs. K. Swathi',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence for high-quality education and research in the field of Computer Science and Engineering, generating highly competent professionals with ethical and human values to serve society.",
      mission: [
        "To impart high-quality education with a strong foundation of Computer Science and Engineering principles that enable students to meet the challenges in their profession/career.",
        "To nurture research activities among faculty and students by providing necessary facilities and environment.",
        "To mold students into effective professionals with necessary communication skills, team spirit, leadership qualities, managerial skills, integrity, social & environmental responsibility, and lifelong learning ability with professional ethics and human values."
      ],
      faculty: [
        { sno: 1, name: 'Mrs.K.Swathi', designation: 'HOD-Sr.Asst. Prof.' },
        { sno: 2, name: 'Dr.V V S S Sameer Chakravarthy', designation: 'Professor' },
        { sno: 3, name: 'Dr.K.Madhusudhana Rao', designation: 'Professor' },
        { sno: 4, name: 'Dr.Y.Salini', designation: 'Assoc.Prof (Senior Scale)' },
        { sno: 5, name: 'Dr.M.P.V.V.Bhaskara Rao', designation: 'Assoc.Prof (selection Grade)' },
        { sno: 6, name: 'Dr.Susant Kumar Sahu', designation: 'Assoc.Prof (selection Grade)' },
        { sno: 7, name: 'Dr.K.A.Naidu', designation: 'Assoc. Prof.' },
        { sno: 8, name: 'Dr.Bhimavarapu Krishna Reddy', designation: 'Assoc. Prof.' },
        { sno: 9, name: 'Dr.T.Archana acharya', designation: 'Assoc. Prof.' },
        { sno: 10, name: 'Dr. Velpula Nagi Reddy', designation: 'Assoc. Prof.' },
        { sno: 11, name: 'Dr.O.Bhaskar', designation: 'Assoc. Prof.' },
        { sno: 12, name: 'Mr.K.Harin Kumar', designation: 'Sr Asst. Prof.' },
        { sno: 13, name: 'Ms.V.Savitri', designation: 'Sr Asst. Prof.' },
        { sno: 14, name: 'Ms.K.Sushma', designation: 'Sr Asst. Prof.' },
        { sno: 15, name: 'Dr.G.V.Ramana', designation: 'Sr Asst. Prof.' },
        { sno: 16, name: 'Mrs.B.Pavani', designation: 'Sr Asst. Prof.' },
        { sno: 17, name: 'Mrs.V.Manasa', designation: 'Sr Asst. Prof.' },
        { sno: 18, name: 'Mrs.K.Divya Kalyani', designation: 'Sr Asst. Prof.' },
        { sno: 19, name: 'Mrs.J.Uttara Alekhya', designation: 'Asst.Prof' },
        { sno: 20, name: 'Mr.S.V.S.V.P.Ramaraju', designation: 'Asst.Prof' },
        { sno: 21, name: 'Mrs.P.Mounika', designation: 'Asst.Prof' },
        { sno: 22, name: 'Ms.B.Swapna', designation: 'Asst.Prof' },
        { sno: 23, name: 'Mr.K.Bhanu Prakash', designation: 'Asst.Prof' },
        { sno: 24, name: 'Mr.A.Sanjay Lova', designation: 'Asst.Prof' },
        { sno: 25, name: 'Mr.Y.KumarSekhar', designation: 'Asst.Prof' },
        { sno: 26, name: 'Mr.K.Venkatesh Babu', designation: 'Asst.Prof' },
        { sno: 27, name: 'Mr.V.Rajendra Prasad', designation: 'Asst.Prof' },
        { sno: 28, name: 'Mrs.B.Shalini', designation: 'Asst.Prof' },
        { sno: 29, name: 'Mrs.Ch.V.Bhargavi', designation: 'Asst.Prof' },
        { sno: 30, name: 'Mr.L.V.Rajesh Kumar', designation: 'Asst.Prof' },
        { sno: 31, name: 'Mr.Kumar Devapogu', designation: 'Asst.Prof' },
        { sno: 32, name: 'Mr.U.Venkateswara Rao', designation: 'Asst.Prof' },
        { sno: 33, name: 'Mr.Gijjula Murali', designation: 'Asst.Prof' },
        { sno: 34, name: 'Mrs.G.Mahalakshmi', designation: 'Asst.Prof' },
        { sno: 35, name: 'Mr.Amar Jukuntla', designation: 'Asst.Prof' },
        { sno: 36, name: 'Mr.P.Srinivas Rao', designation: 'Asst.Prof' },
        { sno: 37, name: 'Ms.Syed Reshma', designation: 'Asst.Prof' },
        { sno: 38, name: 'Mr.Shaik Mahabuba Basha', designation: 'Asst.Prof' },
        { sno: 39, name: 'Ms.Gunatala Archana', designation: 'Asst.Prof' },
        { sno: 40, name: 'Dr.Banoth Tulasya Naik', designation: 'Asst.Prof' },
        { sno: 41, name: 'Ms.D.Lavanya', designation: 'Asst.Prof' },
        { sno: 42, name: 'Ms. Jaladi Indira', designation: 'Asst.Prof' },
        { sno: 43, name: 'Ms. P.Seetha Lakshmi', designation: 'Teaching Asst' },
        { sno: 44, name: 'Mr.P.Manohar Maharshi', designation: 'Teaching Asst' },
        { sno: 45, name: 'Ms.T.Harsha Devi', designation: 'Teaching Asst' },
        { sno: 46, name: 'Mr.M.Pavan Naga Sai', designation: 'Teaching Asst' },
      ]
    },

    bsh: {
      name: 'Basic Sciences and Humanities',
      heroImage: '/images/departments/bsh.png',
      about: "The Department of Basic Sciences and Humanities is recognized as one of the ten departments in the institution. It is a combination of multiple subjects and streams like Chemistry, Physics, Mathematics, Environmental Sciences, and English. It oversees the academic activities of the first year of B.Tech and bridges the gap between intermediate and engineering courses. The department has the privilege of transforming students from diverse backgrounds into better individuals to cope with global requirements. We have a strong counseling system which helps students to mold themselves into real-time professionals. For the last 18 years, the department has been securing outstanding results and always stands in the top three places under the affiliating university. The department has a rich galaxy of intellectuals with 20 Doctorates, six pursuing Doctorates, 11 M.Phils, and 7 CSIR-UGC NET/APSET qualified faculty members. Two faculty members have had their Post-Doctoral Fellowships from universities abroad. Faculty members have published about 110 research papers and 45 conference papers in various national and international reputed journals and conferences. We are proud to announce that a research project worth INR 34 lakhs has been granted to one of our faculty members, Dr. K. Yellareswara Rao. Many of our faculty members have received Gold Medals, Best Teacher Awards, Best Thesis Awards, and other prestigious awards for excellence in academics, research, and service from reputed universities. The department has put forth many efforts to ensure the holistic development of students. It encourages student participation in various co-curricular and extracurricular activities. Our students have participated and won awards/prizes at national and international level events and have bagged many merit certificates, medals, and cash awards. The department conducts live-model exhibitions, sports meets, cultural meets, soft skills programs, workshops, and Faculty Development Programs (FDPs) for the overall development of students and faculty.",
      hodMessage: "Welcome to the Department of Basic Sciences and Humanities. Our department forms the foundation of engineering education, providing students with the essential scientific knowledge and communication skills needed to succeed in their technical studies and future careers. We are dedicated to fostering a learning environment that encourages curiosity, critical thinking, and a passion for lifelong learning. Our experienced faculty is committed to not only academic excellence but also to the holistic development of each student, instilling in them strong ethical and human values. We strive to be a center of excellence that bridges the gap between school and engineering, ensuring our students are well-prepared for the challenges ahead.",
      hodName: 'Dr. T.V.S.P.V. Satyaguru',
      hodImage: defaultHodImage,
      vision: "To be a Centre of Excellence for high-quality education and research, generating highly competent professionals with ethical & human values to serve society.",
      mission: [
        "To impart high-quality education with innovative practices in the teaching-learning process by empowering students to take up professional challenges.",
        "To foster the spirit of research amongst faculty and students by providing state-of-the-art facilities and a conducive environment.",
        "To transform students into professionals by imparting social responsibility, communication skills, leadership qualities, managerial skills, team spirit, and continuous learning."
      ],
      faculty: [
          { sno: 1, name: 'Dr.T V S P.V Satyaguru', designation: 'HOD Assoc.prof(selection Grade)' },
          { sno: 2, name: 'Dr.R L Naidu', designation: 'Professor' },
          { sno: 3, name: 'Dr.Ch Santhi Kumar', designation: 'Professor' },
          { sno: 4, name: 'Dr.Vanthu Naidu', designation: 'Professor' },
          { sno: 5, name: 'Dr.Ch Ramakrishna', designation: 'Assoc.prof' },
          { sno: 6, name: 'Dr.K Rajesh', designation: 'Assoc.prof' },
          { sno: 7, name: 'Dr.B Ravi Kumar', designation: 'Assoc.prof(Senior Scale)' },
          { sno: 8, name: 'Dr. Adla Eswara Rao', designation: 'Assoc.prof(Senior Scale)' },
          { sno: 9, name: 'Dr. Adari Lakshmi', designation: 'Assoc.prof(Senior Scale)' },
          { sno: 10, name: 'Dr. S Indira', designation: 'Assoc.prof(selection Grade)' },
          { sno: 11, name: 'Dr.K.V.Ramana Rao', designation: 'Assoc.prof(selection Grade)' },
          { sno: 12, name: 'Dr. T.Chinnapalanaidu', designation: 'Assoc.prof(selection Grade)' },
          { sno: 13, name: 'Dr.Ch.Leela Rani', designation: 'Assoc.prof(selection Grade)' },
          { sno: 14, name: 'Dr.D.Leela', designation: 'Assoc.prof(Senior Scale)' },
          { sno: 15, name: 'Dr.Bandlamudi devi', designation: 'Assoc.prof(Senior Scale)' },
          { sno: 16, name: 'Dr.Ch.V.V.Ramana', designation: 'Assoc.prof' },
          { sno: 17, name: 'Dr.M.Rama Rao', designation: 'Assoc.prof' },
          { sno: 18, name: 'Dr.Sruthi Vasamsetty', designation: 'Assoc.prof' },
          { sno: 19, name: 'Dr.Chadalawada Sanghavi', designation: 'Assoc.prof' },
          { sno: 20, name: 'Dr.A.Sahitya Kumar', designation: 'Assoc.prof' },
          { sno: 21, name: 'Dr.P.Rama devi', designation: 'Assoc.prof' },
          { sno: 22, name: 'Dr.Kumtalika Jhonimune', designation: 'Assoc.prof' },
          { sno: 23, name: 'Dr.M.Mamatha', designation: 'Assoc.prof' },
          { sno: 24, name: 'Dr.Ch.Anitha', designation: 'Assoc.prof' },
          { sno: 25, name: 'Dr.D.Vamsi Priya', designation: 'Assoc.prof' },
          { sno: 26, name: 'Dr.M.Srinivas', designation: 'Assoc.prof' },
          { sno: 27, name: 'Dr.K.Niharika', designation: 'Assoc.prof' },
          { sno: 28, name: 'Dr.P.Ramana Rao', designation: 'Assoc.prof' },
          { sno: 29, name: 'Dr.K.Harikrishna', designation: 'Assoc.prof' },
          { sno: 30, name: 'Dr.G.Durga Sahoo', designation: 'Assoc.prof' },
          { sno: 31, name: 'Dr.Sudipta Priyadarshini', designation: 'Assoc.prof' },
          { sno: 32, name: 'Dr.B.V.S.N.Rao', designation: 'Assoc.prof' },
          { sno: 33, name: 'Mr.S.Visweswararao', designation: 'Asst..Prof' },
          { sno: 34, name: 'Ms.K.Yasoda', designation: 'Asst.Prof' },
          { sno: 35, name: 'Ms.K.Harini', designation: 'Asst.Prof' },
          { sno: 36, name: 'Mrs M Himabindu', designation: 'Asst.Prof' },
          { sno: 37, name: 'Mr.G.P.Vamsi Naidu', designation: 'Asst.Prof' },
          { sno: 38, name: 'Mrs.A.Anuradha', designation: 'Asst.Prof' },
          { sno: 39, name: 'Mr.J.L.N.Acharyulu', designation: 'Asst.Prof' },
          { sno: 40, name: 'Mr.D.V.G.R.K Siva Kumar', designation: 'Asst.Prof' },
          { sno: 41, name: 'Mr.V.Sai Kumar', designation: 'Asst.Prof' },
          { sno: 42, name: 'Mr.Ch.Bhaskara Rao', designation: 'Asst.Prof' },
          { sno: 43, name: 'Mr.G.Chitti Babu', designation: 'Asst.Prof' },
          { sno: 44, name: 'Mr.P.Sairam Naidu', designation: 'Asst.Prof' },
          { sno: 45, 'name': 'Mr.G.Hemalatha', 'designation': 'Asst.Prof' },
          { sno: 46, 'name': 'Ms.P.Maharani', 'designation': 'Asst.Prof' },
          { sno: 47, 'name': 'Ms.Ch.Meenakshi', 'designation': 'Asst.Prof' },
          { sno: 48, 'name': 'Ms.T.Lavanya', 'designation': 'Asst.Prof' },
          { sno: 49, 'name': 'Ms.D.Anusha', 'designation': 'Asst.Prof' },
          { sno: 50, 'name': 'Ms.S.Jhansi Ramani Priya', 'designation': 'Asst.Prof' },
          { sno: 51, 'name': 'Ms.A.Tejasri', 'designation': 'Asst.Prof' },
          { sno: 52, 'name': 'Ms.M.Usha Bohara', 'designation': 'Asst.Prof' },
          { sno: 53, 'name': 'Ms.K.Jyothi', 'designation': 'Asst.Prof' },
          { sno: 54, 'name': 'Ms.S.Siva Rao Sambhana', 'designation': 'Asst.Prof' },
          { sno: 55, 'name': 'Mr.V.S.S.N.Murty', 'designation': 'Asst.Prof' },
          { sno: 56, 'name': 'Ch Siva parvathi', 'designation': 'Asst.Prof' },
          { sno: 57, 'name': 'Mr.Ch.Ganapathi Ramya Naidu', 'designation': 'Asst.Prof' },
          { sno: 58, 'name': 'Mr. Vaddadi Naga Raju', 'designation': 'Asst.Prof' },
          { sno: 59, 'name': 'G.Uma devi', 'designation': 'Asst.Prof' },
          { sno: 60, 'name': 'Ms. Merupu Gannika Daparte', 'designation': 'Asst.Prof' },
          { sno: 61, 'name': 'G.Devi', 'designation': 'Asst.Prof' },
          { sno: 62, 'name': 'Ms. Padda Bs Rajya lakshmi Avanthi', 'designation': 'Asst.Prof' },
          { sno: 63, 'name': 'Ms.M.Dhana lakshmi', 'designation': 'Asst.Prof' },
          { sno: 64, 'name': 'Mr. Pudi Srinivasa', 'designation': 'Asst.Prof' },
          { sno: 65, 'name': 'Ms. S N D Tejuoja', 'designation': 'Asst.Prof' },
          { sno: 66, 'name': 'Ms. A.Durgambika', 'designation': 'Asst.Prof' },
          { sno: 67, 'name': 'Ms. Mounika Arimilli', 'designation': 'Asst.Prof' },
          { sno: 68, 'name': 'Mr. K.Srinivasu', 'designation': 'Asst.Prof' },
          { sno: 69, 'name': 'Mr. N.Dora Babu', 'designation': 'Asst.Prof' },
          { sno: 70, 'name': 'Mr. V.V.Suryanarayana', 'designation': 'Asst.Prof' },
          { sno: 71, 'name': 'Mr. Ramu Kotiswara Rao', 'designation': 'Asst.Prof' },
          { sno: 72, 'name': 'Mr. Nalluri Umamaheswara Rao', 'designation': 'Asst.Prof' },
          { sno: 73, 'name': 'Mr. Syalada Sanyasi Rao', 'designation': 'Asst.Prof' },
          { sno: 74, 'name': 'Mr. K.Surya Prakasa Rao', 'designation': 'Asst.Prof' },
          { sno: 75, 'name': 'Mr. M.Padmavathi', 'designation': 'Asst.Prof' },
          { sno: 76, 'name': 'Ms.M.Ramya sri', 'designation': 'Asst.Prof' },
          { sno: 77, 'name': 'Mr. K.Prasadechandra', 'designation': 'Asst.Prof' },
          { sno: 78, 'name': 'Ms. G.L.Prasanna Nilima', 'designation': 'Asst.Prof' },
          { sno: 79, 'name': 'Ms. Madhuri Mahanty', 'designation': 'Asst.Prof' },
          { sno: 80, 'name': 'Ms. K.Devi', 'designation': 'Asst.Prof' },
          { sno: 81, 'name': 'Dr. K.S.V.Ramana', 'designation': 'PD' },
          { sno: 82, 'name': 'Mr. M.V.V.Prasad', 'designation': 'PD' },
          { sno: 83, 'name': 'Mr.V.srinivasa Rao', 'designation': 'Librarian' },
          { sno: 84, 'name': 'Mr.Ch.Narayana Naidu', 'designation': 'Teaching Asst' },
          { sno: 85, 'name': 'Ms.M.Pavani', 'designation': 'Teaching Asst' },
          { sno: 86, 'name': 'Ms. Y.Lavanya Lahari', 'designation': 'Teaching Asst' },
          { sno: 87, 'name': 'Mr.V.Siva', 'designation': 'Teaching Asst' },
          { sno: 88, 'name': 'Ms.Y.Madhavi', 'designation': 'Teaching Asst' },
          { sno: 89, 'name': 'Ms.K.Madhuri', 'designation': 'Teaching Asst' },
      ]
    },

    mba: {
      name: 'Master of Business Administration',
      heroImage: '/images/departments/mba.png',
      about: "The institution started offering the MBA course in 2006-07. The three aims of the program are: to enable students to tap their innate potential to bloom into business leaders, to equip students with the skills required to develop into managers, and to provide the impetus to reach the higher echelons of an organization. The course offers a wide spectrum of business knowledge, conceptual, and analytical skills to develop students into competent and effective managers. It lays emphasis on innovative pedagogy which includes industry internships, live projects, business games, case studies, interaction with experts, seminars, etc. BVRIT is a center of excellence in value-based education, training, research, and consultancy. It has dedicated full-time faculty members with varied experience in industry and academia. BVRIT has brought about a revolution in the field of education and rewritten the history of education in Andhra Pradesh. Today, BVRIT is one of the pioneers in the field of education in the country, having spread its wings across the state. Its students have successfully made their mark in their chosen fields all across the globe.",
      hodMessage: "Greetings from the Department of Management Studies, B V Raju Institute of Technology (Autonomous). As you are aware, the Department of Management Studies has contributed to the spread of management education through its full-time programs. The department is committed to achieving professional excellence in imparting management education along with a social commitment towards extension and diversity. The curriculum is designed and enriched with industry support and participation. The pedagogy is highly interactive with a practical orientation. The industry has recognized the capability of our students by absorbing them in core areas and offering them challenging assignments. Our students are placed in well-reputed organizations like Axis Bank, Federal Bank, IBM, Just Dial, Capital IQ, Jaro Education, Cognizant, GENPACT, Ram Group, I Process, Sutherland Global, Efftronics, Yelamanchili Software Solutions, etc.",
      hodName: 'Dr. B. Chandra',
      hodImage: defaultHodImage,
      vision: "To build managers and entrepreneurs through excellent standards of quality education by keeping pace with a rapidly changing environment.",
      mission: [
        "To enable students to tap their innate potential to bloom into business leaders.",
        "To develop better and more efficient managers and enhance job prospects.",
        "To deliver distinctive education through the pioneering use of technology."
      ],
      faculty: [
          { sno: 1, name: 'Dr..B.Chandra', designation: 'HOD Assoc . Prof.' },
          { sno: 2, name: 'Dr.P.S.Ravindra', designation: 'Professor' },
          { sno: 3, name: 'Dr.S.M.Murali Krishna', designation: 'Professor' },
          { sno: 4, name: 'Dr.Ch.Hari Govinda Rao', designation: 'Assoc . Prof.' },
          { sno: 5, name: 'Dr.M.Srinu', designation: 'Assoc . Prof.' },
          { sno: 6, name: 'Dr.Praveena .KVS', designation: 'Assoc . Prof.' },
          { sno: 7, name: 'Dr.Pinninti Sanyasi Rao', designation: 'Assoc . Prof.' },
          { sno: 8, name: 'Dr.K.G.K.Patnaik', designation: 'Assoc . Prof.' },
          { sno: 9, name: 'Dr.J.Manogna', designation: 'Assoc . Prof.' },
          { sno: 10, name: 'Mr.V.Sivaji', designation: 'Sr.Asst.Prof' },
          { sno: 11, name: 'Ms.Auadhati Datta', designation: 'Asst. Prof.' },
          { sno: 12, name: 'Mr.U.Rakesh', designation: 'Asst. Prof.' },
          { sno: 13, name: 'Mr.B.Siva Kumar', designation: 'Asst. Prof.' },
          { sno: 14, name: 'Ms.P.Lavanya', designation: 'Asst. Prof.' },
          { sno: 15, name: 'Ms.N.Kanaka Maha Lakshmi', designation: 'Teaching.Asst' },
      ]
    },

    mca: {
      name: 'Master of Computer Applications',
      heroImage: '/images/departments/mca.png',
      about: "The Department of MCA at B V Raju Institute of Technology (BVRIT) has been active in teaching and research since its inception in 2006. Currently, about 8 committed faculty members are working in the department. The department offers a two-year postgraduate program in Master of Computer Applications. BVRIT's goal is to become a world-class engineering institute in a multi-campus setting. It is one of the best institutions in the state. In that respect, the Department of MCA provides better guidance to all students with practical knowledge and skills. This is an important aspect for current requirements under the new concept of outcome-based education. Here, students are trained to work as a team and strive for excellence. These students represent the cream of society and are therefore expected to contribute to the enhancement of the reputation and credibility of this institute. The course will not only groom students to become world-class professionals but will also nurture their sense of purpose and vision. Members of our faculty reflect the variety of interests and qualities inherent in Information Technology. They are dedicated to demonstrating and promoting the specialty to the BVRIT community of students and faculty as well as to the people we serve.",
      hodMessage: "Welcome to the Department of Master of Computer Applications. Our goal is to equip students with advanced skills in computer applications to meet the dynamic demands of the IT industry. We provide a robust curriculum that blends theoretical foundations with practical, hands-on experience. Our dedicated faculty members are committed to mentoring students, fostering innovation, and preparing them to be competent and ethical professionals. We believe in creating a learning environment where students can thrive, excel, and become future leaders in technology.",
      hodName: 'Dr. Chandrasekharan Dinesh',
      hodImage: defaultHodImage,
      vision: "We aim to generate groomed, technically competent, and skilled intellectual professionals. We serve as a valuable resource for modern industry and current society.",
      mission: [
        "Providing a strong theoretical and practical knowledge in the computer science discipline with an emphasis on software development.",
        "Providing technical solutions in the field of Information Technology to the local society.",
        "Providing need-based quality training in the field of Information Technology.",
        "Imparting quality education to meet global standards and achieve excellence in teaching-learning and research.",
        "Providing students with the tools to become productive, participating global citizens and lifelong learners."
      ],
      faculty: [
          { sno: 1, name: 'Mrs.A.Sirisha', designation: 'Sr.Asst. Prof.' },
          { sno: 2, name: 'Mrs.D.Lakshmi Bhavani', designation: 'Asst. Prof.' },
          { sno: 3, name: 'Mr.A.V.V.Chakrapani', designation: 'Asst.Prof' },
          { sno: 4, name: 'Ms.T.V Lakshmi Devi', designation: 'Asst.Prof' },
          { sno: 5, name: 'K Gowthami Prasanthi', designation: 'Asst.Prof' },
          { sno: 6, name: 'Batuula Vennela', designation: 'Asst.Prof' },
          { sno: 7, name: 'Padda Nalini', designation: 'Asst.Prof' },
          { sno: 8, name: 'Bankuru Bhagyasri', designation: 'Asst.Prof' },
          { sno: 9, name: 'N.Tulasi Naidu', designation: 'Asst.Prof' },
          { sno: 10, name: 'K.Amrutha', designation: 'Asst.Prof' },
          { sno: 11, name: 'M.Sasidhar', designation: 'Asst.Prof' },
          { sno: 12, name: 'G.Prasanna Kumari', designation: 'Asst.Prof' },
          { sno: 13, name: 'A.Vanaja', designation: 'Asst.Prof' },
          { sno: 14, name: 'M.Dineswar Sai', designation: 'Asst.Prof' },
          { sno: 15, name: 'M.Deevan', designation: 'Asst.Prof' },
          { sno: 16, name: 'T.Swathi', designation: 'Asst.Prof' },
          { sno: 17, name: 'Ms.K.Lekha sree', designation: 'Teaching Asst' },
          { sno: 18, name: 'Ms.K.Lavanya', designation: 'Teaching Asst' },
          { sno: 19, name: 'Mr.G.Bhargav', designation: 'Teaching Asst' },
          { sno: 20, name: 'Mr. Eswara Rao', designation: 'Teaching Asst' },
      ]
    },

    ecm: {
      name: 'Electronics and Computer Engineering (ECM)',
      heroImage: '/images/departments/ecm.png',
      about: "Electronics and Computer Engineering (ECM) is a course that aims to integrate two separate engineering fields to meet the joint demands of the electronics and computer industries in today's world. This program combines coursework in different aspects of both fields over four years, with an emphasis on the design of computing systems. Electronics and computers, and their joint applications, are playing an ever-increasing role in our lives as Information and Communications Technology (ICT), with everything from consumer goods to space shuttles using integrated electronic hardware (circuits) and computer software. The increased use of ICT in every aspect of our lives ensures the continued relevance of this field. The Department of ECM has expert faculty from both electronics and computer science backgrounds, allowing students to avail themselves of expert knowledge in both areas.",
      hodMessage: "Welcome to the Department of Electronics and Computer Engineering. We aim to create a learning environment that promotes creativity, innovation, and collaboration. Our curriculum is designed to provide a strong foundation in both electronics and computer science, preparing our students to tackle the challenges of the modern tech industry. We are committed to fostering research and development and encouraging our students to become lifelong learners and ethical professionals. Join us to be part of a dynamic community that is shaping the future of technology.",
      hodName: 'Dr. H. Devanna',
      hodImage: defaultHodImage,
      vision: "To produce globally competent engineers in the area of Electronics & Computers and to create technical manpower for the current and future demands of the nation.",
      mission: [
        "Introducing innovative practices of teaching and learning.",
        "Undertaking research in the thrust areas of software and hardware.",
        "Serving the software and hardware industry by producing quality engineers.",
        "Inculcating a strong set of ethical values."
      ],
      faculty: [
        { sno: 1, name: 'Dr.H.Devanna', designation: 'HOD Assoc. Prof.' },
        { sno: 2, name: 'Dr.B.Prasada Rao', designation: 'Assoc. Prof.' },
        { sno: 3, name: 'Dr.P.Santosh', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Mrs.M.Kalpana', designation: 'Asst.Prof' },
        { sno: 5, name: 'Ms.A.Lakshmi Deepika', designation: 'Asst.Prof' },
        { sno: 6, name: 'Mr.P.Ganesh', designation: 'Asst.Prof' },
        { sno: 7, name: 'Mrs.A.Sarvani', designation: 'Asst.Prof' },
        { sno: 8, name: 'Ch.Gayatri', designation: 'Asst.Prof' },
        { sno: 9, name: 'Ms.B.Maha Lakshmi', designation: 'Asst.Prof' },
      ]
    },

    // M.Tech Programs
    mtechVlsi: {
      name: 'M.Tech VLSI and Embedded Systems',
      heroImage: '/images/departments/mtech-vlsi.png',
      about: "The M.Tech VLSI and Embedded Systems program is designed to provide in-depth knowledge in the design and development of Very Large Scale Integration (VLSI) circuits and embedded systems. This program focuses on advanced topics in digital design, analog design, system-on-chip design, and embedded software development. Students gain hands-on experience with industry-standard tools and technologies used in semiconductor and embedded systems industries. The curriculum covers advanced topics in VLSI design, embedded programming, real-time systems, and hardware-software co-design.",
      hodMessage: "Welcome to the M.Tech VLSI and Embedded Systems program. This program is designed to meet the growing demands of the semiconductor and embedded systems industries. Our curriculum combines theoretical foundations with practical experience, ensuring that our graduates are well-prepared for challenging roles in industry and research. We focus on cutting-edge technologies and provide state-of-the-art facilities for learning and research.",
      hodName: 'Dr. R. Uma Maheswari',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence in VLSI and embedded systems education and research, producing highly skilled professionals for the semiconductor industry.",
      mission: [
        "To provide comprehensive education in VLSI design and embedded systems.",
        "To foster research and innovation in semiconductor technologies.",
        "To develop industry-ready professionals with strong technical and ethical foundations.",
        "To establish strong industry-academia partnerships for technology transfer."
      ],
      faculty: [
        { sno: 1, name: 'Dr.R.Uma Maheswari', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.A.Naga Jyothi', designation: 'Professor' },
        { sno: 3, name: 'Dr.K.Srinivasa Naik', designation: 'Professor' },
        { sno: 4, name: 'Dr.M.Karuna', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.A.Sampath Dakshina Murthy', designation: 'Assoc. Prof.' },
      ]
    },

    mtechTransportation: {
      name: 'M.Tech Transportation Engineering',
      heroImage: '/images/departments/mtech-transportation.png',
      about: "The M.Tech Transportation Engineering program focuses on the planning, design, operation, and management of transportation systems. This program covers various modes of transportation including highways, railways, airways, and waterways. Students learn about traffic engineering, transportation planning, pavement design, intelligent transportation systems, and sustainable transportation solutions. The curriculum emphasizes both theoretical concepts and practical applications to address modern transportation challenges.",
      hodMessage: "Welcome to the M.Tech Transportation Engineering program. Transportation is the backbone of economic development, and our program is designed to create competent professionals who can contribute to the development of efficient and sustainable transportation systems. We focus on modern transportation technologies, smart mobility solutions, and sustainable practices to meet the challenges of the 21st century.",
      hodName: 'Dr. Govinda Lalam',
      hodImage: defaultHodImage,
      vision: "To be a leading center for transportation engineering education and research, contributing to sustainable and intelligent transportation systems.",
      mission: [
        "To provide advanced education in transportation engineering and planning.",
        "To conduct research in sustainable and intelligent transportation systems.",
        "To develop professionals capable of addressing modern transportation challenges.",
        "To promote innovation in transportation technologies and practices."
      ],
      faculty: [
        { sno: 1, name: 'Dr.L.Govinda', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.G.Tejaswi Laxmi Priyanka', designation: 'Assoc. Prof.' },
        { sno: 3, name: 'Dr.K.Ramesh Babu', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Dr.G.Amulya', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.S.Gayathri', designation: 'Assoc. Prof.' },
      ]
    },

    mtechSoftwareEngineering: {
      name: 'M.Tech Software Engineering',
      heroImage: '/images/departments/mtech-software.png',
      about: "The M.Tech Software Engineering program is designed to provide advanced knowledge in software development methodologies, software architecture, and project management. This program focuses on modern software engineering practices including agile development, DevOps, cloud computing, and software quality assurance. Students learn advanced programming concepts, software design patterns, and emerging technologies. The curriculum emphasizes practical experience through industry projects and internships.",
      hodMessage: "Welcome to the M.Tech Software Engineering program. In today's digital world, software engineering is at the heart of technological innovation. Our program is designed to create highly skilled software professionals who can lead complex software projects and drive innovation in the industry. We focus on both technical excellence and leadership skills to prepare our graduates for senior roles in the software industry.",
      hodName: 'Mr. B. Dinesh Reddy',
      hodImage: defaultHodImage,
      vision: "To be a premier center for software engineering education, producing innovative leaders for the global software industry.",
      mission: [
        "To provide advanced education in software engineering principles and practices.",
        "To foster research and innovation in software technologies.",
        "To develop technical leaders with strong problem-solving and management skills.",
        "To establish strong industry connections for practical learning and placement opportunities."
      ],
      faculty: [
        { sno: 1, name: 'Mr.B.Dinesh Reddy', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.N.Tirupathi Rao', designation: 'Professor' },
        { sno: 3, name: 'Dr.S.Naga Mallik Raj', designation: 'Assoc. Professor' },
        { sno: 4, name: 'Dr.CH.Swapnapriya', designation: 'Assoc. Professor' },
        { sno: 5, name: 'Dr.P.Hemantry kohan', designation: 'Assoc. Professor' },
      ]
    },

    mtechAiml: {
      name: 'M.Tech Artificial Intelligence and Machine Learning',
      heroImage: '/images/departments/mtech-aiml.png',
      about: "The M.Tech Artificial Intelligence and Machine Learning program provides comprehensive education in AI/ML technologies, deep learning, natural language processing, computer vision, and data analytics. This program focuses on both theoretical foundations and practical applications of AI/ML in various domains. Students gain experience with cutting-edge tools and frameworks for developing intelligent systems. The curriculum covers advanced topics in machine learning algorithms, neural networks, and AI ethics.",
      hodMessage: "Welcome to the M.Tech Artificial Intelligence and Machine Learning program. AI and ML are transforming every industry and creating unprecedented opportunities for innovation. Our program is designed to prepare students for leadership roles in AI research and development. We provide hands-on experience with the latest AI/ML technologies and emphasize ethical AI development for the benefit of society.",
      hodName: 'Dr. T.V. Madhusudan Rao',
      hodImage: defaultHodImage,
      vision: "To be a leading center for AI/ML education and research, contributing to the advancement of intelligent systems.",
      mission: [
        "To provide advanced education in artificial intelligence and machine learning.",
        "To conduct cutting-edge research in AI/ML technologies and applications.",
        "To develop ethical AI practitioners and researchers.",
        "To foster innovation and entrepreneurship in AI-driven solutions."
      ],
      faculty: [
        { sno: 1, name: 'Dr.T.V.Madhusudhana Rao', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.Bhiogade Girish Eknath', designation: 'Assoc. Prof.' },
        { sno: 3, name: 'Dr.Peter Praveen', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Dr.Brajesh Kumar', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.P.Visweswara Rao', designation: 'Assoc. Prof.' },
      ]
    },

    mtechPowerSystems: {
      name: 'M.Tech Power Systems',
      heroImage: '/images/departments/mtech-power.png',
      about: "The M.Tech Power Systems program provides advanced education in electrical power generation, transmission, distribution, and utilization. This program covers modern power system analysis, smart grids, renewable energy integration, power system protection, and power electronics applications. Students gain hands-on experience with industry-standard software and hardware used in power system analysis and design. The curriculum emphasizes sustainable energy solutions and smart grid technologies.",
      hodMessage: "Welcome to the M.Tech Power Systems program. With the growing demand for clean and reliable energy, power systems engineering has become more critical than ever. Our program prepares students to tackle the challenges of modern power systems, including renewable energy integration, smart grids, and energy efficiency. We focus on both traditional power system concepts and emerging technologies to prepare our graduates for the evolving energy landscape.",
      hodName: 'Dr. Pudi Sekhar',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence in power systems education and research, contributing to sustainable energy solutions.",
      mission: [
        "To provide advanced education in power systems engineering and smart grid technologies.",
        "To conduct research in renewable energy integration and power system optimization.",
        "To develop skilled professionals for the power and energy sectors.",
        "To promote sustainable energy practices and technologies."
      ],
      faculty: [
        { sno: 1, name: 'Dr.P.Sekhar', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.K.Durga Syam Prasad', designation: 'Professor' },
        { sno: 3, name: 'Dr.R.S.Ravi Sankar', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Dr.K.K.Deepika', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.K.Venkatanagaraju', designation: 'Assoc. Prof.' },
      ]
    },

    mtechInformationTechnology: {
      name: 'M.Tech Information Technology',
      heroImage: '/images/departments/mtech-it.png',
      about: "The M.Tech Information Technology program focuses on advanced concepts in information systems, database technologies, network security, cloud computing, and IT management. This program is designed to meet the growing demand for IT professionals with specialized skills in emerging technologies. Students learn about big data analytics, cybersecurity, mobile computing, and enterprise information systems. The curriculum combines theoretical knowledge with practical experience through industry projects.",
      hodMessage: "Welcome to the M.Tech Information Technology program. Information Technology is the driving force behind digital transformation across all industries. Our program is designed to create IT leaders who can navigate the complex landscape of modern information systems and drive innovation in their organizations. We focus on both technical depth and business understanding to prepare our graduates for senior IT roles.",
      hodName: 'Dr. G. Neelima',
      hodImage: defaultHodImage,
      vision: "To be a leading center for information technology education, producing innovative IT professionals for the digital age.",
      mission: [
        "To provide advanced education in information technology and emerging digital technologies.",
        "To conduct research in areas of cybersecurity, big data, and cloud computing.",
        "To develop IT leaders with strong technical and management skills.",
        "To foster innovation and entrepreneurship in IT solutions."
      ],
      faculty: [
        { sno: 1, name: 'Dr.GullipalliNeelima', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.B.Prasad', designation: 'Professor' },
        { sno: 3, name: 'Dr.T.Eswara Rao', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Mrs.G.Jyothi', designation: 'Sr. Asst. Prof.' },
        { sno: 5, name: 'Mr.Ch.Srinivasa Reddy', designation: 'Sr. Asst. Prof.' },
      ]
    },

    mtechPowerIndustrialDrives: {
      name: 'M.Tech Power and Industrial Drives',
      heroImage: '/images/departments/mtech-drives.png',
      about: "The M.Tech Power and Industrial Drives program specializes in the design and control of electrical drives and power electronic systems used in industrial applications. This program covers advanced topics in motor drives, power converters, control systems, and automation. Students learn about variable frequency drives, servo systems, and industrial automation technologies. The curriculum emphasizes practical experience with industry-standard equipment and software used in drive systems design and control.",
      hodMessage: "Welcome to the M.Tech Power and Industrial Drives program. Industrial drives and automation are essential for modern manufacturing and process industries. Our program is designed to create specialists in power electronics and drive systems who can contribute to industrial efficiency and automation. We provide comprehensive training in both theoretical concepts and practical applications of industrial drive systems.",
      hodName: 'Dr. Pudi Sekhar',
      hodImage: defaultHodImage,
      vision: "To be a center of excellence in power electronics and drives education, supporting industrial automation and efficiency.",
      mission: [
        "To provide specialized education in power electronics and industrial drives.",
        "To conduct research in advanced drive control and automation technologies.",
        "To develop skilled professionals for the power electronics and automation industries.",
        "To promote energy-efficient and intelligent drive systems."
      ],
      faculty: [
        { sno: 1, name: 'Dr.P.Sekhar', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr.M.Lakshmi SivaSai Kumar', designation: 'Assoc. Prof.' },
        { sno: 3, name: 'Dr.B.Trinadha', designation: 'Assoc. Prof.' },
        { sno: 4, name: 'Dr.B.Omkar Lakshmi Jagan', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.Jayanta Kumar Sahu', designation: 'Assoc. Prof.' },
      ]
    },

    mtechMachineDesign: {
      name: 'M.Tech Machine Design',
      heroImage: '/images/departments/mtech-machine-design.png',
      about: "The M.Tech Machine Design program focuses on advanced concepts in mechanical design, finite element analysis, computer-aided design, and manufacturing processes. This program covers modern design methodologies, optimization techniques, and advanced materials used in machine design. Students gain hands-on experience with CAD/CAM software, simulation tools, and rapid prototyping technologies. The curriculum emphasizes innovative design solutions and sustainable manufacturing practices.",
      hodMessage: "Welcome to the M.Tech Machine Design program. Machine design is at the heart of all mechanical systems and products that improve our daily lives. Our program is designed to create design engineers who can innovate and develop efficient, sustainable, and cost-effective mechanical systems. We combine traditional design principles with modern computational tools to prepare our graduates for leadership roles in design and manufacturing industries.",
      hodName: 'Dr. S. Rambabu',
      hodImage: defaultHodImage,
      vision: "To be a premier center for machine design education, fostering innovation in mechanical design and manufacturing.",
      mission: [
        "To provide advanced education in machine design principles and modern design tools.",
        "To conduct research in innovative design methodologies and sustainable manufacturing.",
        "To develop creative design engineers with strong analytical and problem-solving skills.",
        "To establish strong industry partnerships for practical learning and technology transfer."
      ],
      faculty: [
        { sno: 1, name: 'Dr.Rambabu Sarimalla', designation: 'Program Coordinator' },
        { sno: 2, name: 'Dr. B. Sateesh', designation: 'Professor' },
        { sno: 3, name: 'Dr.R. Sundara Ramam', designation: 'Professor' },
        { sno: 4, name: 'Dr.K.S. Raghuram', designation: 'Assoc. Prof.' },
        { sno: 5, name: 'Dr.V.S.V.Satyanarayana', designation: 'Assoc. Prof.' },
      ]
    },
  }
};